projet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taskmanager.urls')),
    path('home/', include('taskmanager.urls')),
    path('taskmanager/', include('taskmanager.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskmanager/urls.py
from django.urls import path
from . import views
from . import views_graph
from . import views_export

urlpatterns = [
    path('', views.redirect_home, name='redirect_home'),
    path('home/', views.home, name='home'),
    # path('connect/', views.connect, name = 'connect'),
    path('connect/', views.LoginPage.as_view(), name='connect'),
    path('disconnect/', views.disconnect, name='disconnect'),
    path('projects/', views.projects, name='projects'),
    path('projects/<int:id>', views.focus_project, name='focus_project'),
    path('task/<int:id>', views.focus_task, name='focus_task'),
    path('newproject', views.newproject, name='newproject'),
    path('manageproject/<int:id>', views.manageproject, name='manageproject'),
    path('newtask/<int:id_project>', views.newtask, name='newtask'),
    path('managetask/<int:id>', views.managetask, name='managetask'),

    path('members/', views.projects_members, name='membersproject'),
    path('tasks/', views.list_tasks, name='listtasks'),
    path('finished/', views.finished_tasks, name='finishedtasks'),
    path('distinct/<int:ide>', views.distinct_tasks, name='distincttasks'),
    path('activities/<int:ide>', views.activities, name='activities'),

    path('avancement/<int:id>',views.ModifyAvancement, name='form_avancement'),

    path('dashboard', views_graph.dashboard, name='dashboard'),
    path('graphs', views_graph.graphs, name='graphs'),

    path('gantt', views_graph.gantt, name='gantt'),

    path('burndown', views_graph.burndown, name='burndown'),
    path('radartask', views_graph.radartask, name='radartask'),
    path('radaractivity', views_graph.radaractivity, name='radaractivity'),
    path('manageapp', views_graph.manageapp, name='manageapp'),

    path('taskfilter', views.task_filter, name='task_filter'),
    path('taskfilterresult/page=<int:index>', views.task_filter_result, name='task_filter_result'),

    path('export/xml/<int:id>', views_export.export_xml, name='export_xml'),
    path('export/json/<int:id>', views_export.export_json, name='export_json'),
    path('export/csv/<int:id>', views_export.export_csv, name='export_csv'),
    path('export/excel/<int:id>', views_export.export_excel, name='export_excel'),

]

taskmanager/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.utils import timezone
from django.core.validators import MaxValueValidator,MinValueValidator
import os


# ===== Projet =====
class Project(models.Model):
    # Nom du projet
    name = models.CharField(max_length = 160, verbose_name = "Titre")
    # Liste des membres
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = "Membres")
    # Visibilité du projet (Prive ou public)
    public = models.CharField(max_length = 2, choices = [("PU", "public"), ("PR", "privé")], default = "PR", verbose_name = "Partage")
    # Avancement du projet
    completed = models.IntegerField(default=0, verbose_name = "Avancement")

    def __str__(self):
        return self.name


# ===== Statut =====
# En gros une classe qui remplace un CharField avec choices
class Status(models.Model):
    # Statut [Nouvelle, En attente, ...]
    how = models.CharField(max_length = 160, verbose_name = "Statut")

    def __str__(self):
        return self.how


# ===== Commentaire =====
# Journal d'une tache Ou commentaires, selon comment on voit ca...
class Comment(models.Model):
    # L'user qui a ecrit le commentaire
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, verbose_name = "Utilisateur")
    # Quand le commentaire a ete ajoute
    submit_time = models.DateTimeField(default = timezone.now, verbose_name = "Date")
    # Son contenu
    content = models.TextField(null = True, verbose_name = "Contenu", blank = True)

    def __str__(self):
        return self.user.username + " : " + self.content


# ===== Sous tache d'une tache =====
class Subtask(models.Model):
    # Tache parent
    task = models.ForeignKey('Task', on_delete = models.CASCADE, verbose_name = "Parent", default = None )
    # Nom de la sous tache
    name = models.CharField(max_length = 100, verbose_name = "Sous-tâche")

    def __str__(self):
        return self.name


# ===== Categorie d'une tache =====
class Category(models.Model):
    # Nom de la categorie
    name = models.CharField(max_length = 100, verbose_name = "Catégorie")

    def __str__(self):
        return self.name



# ===== Tache =====
class Task(models.Model):
    # Projet parent
    project = models.ForeignKey('Project', on_delete = models.CASCADE, verbose_name = "Projet")
    # Nom de la tache
    name = models.CharField(max_length = 200, verbose_name = "Tâche")
    # Description de la tache
    description = models.TextField(null = True, verbose_name = "Description", blank = True)
    # Categorie de la tache
    category = models.ForeignKey('Category', on_delete = models.SET_NULL, verbose_name = "Catégorie", null = True, blank = True)
    # Responsable de la tache [assignee]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, verbose_name = "Responsable")
    # Une piece jointe pour expliciter le propos
    attachment = models.FileField(upload_to = "file/", null = True, blank = True, verbose_name = "Pièce jointe")
    # Début de la tache
    start_date = models.DateTimeField(verbose_name = "Date de début")
    # Deadline de la tache
    due_date = models.DateTimeField(verbose_name = "Deadline")
    # Priorité de la tache
    priority = models.IntegerField(verbose_name = "Priorité")
    # Statut [Nouvelle, En attente...]
    status = models.ForeignKey('Status', on_delete = models.CASCADE, verbose_name = "Statut")
    # Journal (ou commentaires...)
    comments = models.ManyToManyField(Comment, related_name = "Commentaires", blank = True)
    # Avancement de la tâche
    completed = models.IntegerField(default=0, verbose_name = "Avancement")


    # Permet d'avoir le nom et l'extension de la piece jointe
    def attachment_info(self):
        _, extension = os.path.splitext(self.attachment.name)
        name = os.path.basename(self.attachment.name)
        return name, extension


    def __str__(self):
        return self.name


# ===== Traces =====

class Verb(models.Model):
    # AddCm -> Ajout de commentaire
    # MdfTk -> Modif tache
    # MdfPr -> Modif projet
    # AddTk -> Ajout tache
    # AddPr -> Ajout projet
    # MdfAv -> Modif avancement
    # Réduction du verb
    alias = models.CharField(max_length = 10, verbose_name = "Alias", default = "VB")
    # Verbe / action
    verb = models.CharField(max_length = 100, verbose_name = "Verbe")

    def __str__(self):
        return self.alias

class Trace(models.Model):
    # Alias de la trace (plus pratique pour les créer / supprimer)
    alias = models.CharField(max_length = 100, verbose_name = "Alias", default = None, blank = True, null = True)
    # Qui a laissé cette trace
    actor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, verbose_name = "Acteur")
    # Quand a été laissée cette trace
    timestamp = models.DateTimeField(verbose_name = "Timestamp", default = timezone.now)
    # Projet concerné
    object_project = models.ForeignKey('Project', on_delete = models.CASCADE, verbose_name = "Projet", default = None)
    # Tache concernée si existe
    object_task = models.ForeignKey('Task', on_delete = models.CASCADE, verbose_name = "Tache", default = None, blank = True, null = True)
    # Donnée complémentaire numérique si besoin
    extension_integer = models.IntegerField(default = None, verbose_name = "Extension numérique", blank = True, null = True)
    # Verbe
    verb = models.ForeignKey('Verb', on_delete = models.CASCADE, verbose_name = "Verbe", default = None)

    def __str__(self):
        return self.actor.username + " : " + self.verb.alias

taskmanager/forms.py
from django import forms
from .models import Project, Status, Comment, Task
import datetime
from django.contrib.auth.models import User

text_widget = forms.TextInput(
    attrs={
        'class': 'form-control',
        'required': "True"
    })

large_txt_widget = forms.Textarea(
    attrs={
        'class': 'form-control',
        'rows': 4
    })


# Form pour se connecter
class LoginForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", max_length=30,
                               widget=forms.TextInput(
                                   attrs={
                                       'rows': '1',
                                       'class': 'form-control',
                                       'placeholder': "Nom d'utilisateur"
                                   }
                               ))
    password = forms.CharField(label="Mot de passe",
                               widget=forms.PasswordInput(
                                   attrs={
                                       'rows': '1',
                                       'class': 'form-control',
                                       'placeholder': "Mot de passe"
                                   }
                               ))


# Form de création ou modification de projet
class ProjectForm(forms.ModelForm):
    # On ne met pas le field members, je le crée moi meme avec un drag & drop en js
    class Meta:
        model = Project
        fields = ('name',)
        widgets = {
            'name': text_widget
        }


# Form pour ajouter un commentaire a une tache
class CommentForm(forms.Form):
    content = forms.CharField(label="Commentaire",
                              widget=forms.Textarea(
                                  attrs={
                                      'rows': '1',
                                      'class': 'form-control',
                                      'placeholder': "Ajouter un commentaire"
                                  }
                              ))


# Form pour ajouter ou modifier une tache
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ('project', 'comments',)
        widgets = {
            'name': text_widget,
            'description': large_txt_widget,
            'status': forms.RadioSelect(),
        }

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)

        # Pour que y ait pas le champ "------"
        self.fields['user'].empty_label = None
        self.fields['status'].empty_label = None

        # Pour que les membres selectionnables ne soient que ceux du projet
        project = kwargs['initial']['project']
        self.fields['user'].queryset = project.members

    def clean(self):
        # A priori inutile si mon cote client est bien fait, mais toujours bien d'avoir une autre verification niveau serveur...
        cleaned_data = super(TaskForm, self).clean()

        start_date = cleaned_data.get('start_date')
        due_date = cleaned_data.get('due_date')

        if (start_date > due_date):
            self.add_error("start_date",
                           "Vérifiez vos dates : la date de début doit être avant la date de fin (Logique non ?)")

        return cleaned_data


class CompletedForm(forms.Form):
    completed = forms.IntegerField(required=False)

taskmanager/templates/taskmanager/activities.html
{% extends "base.html" %}
{%  load humanize %}
{% block css %}
<style>
a:hover {
	text-decoration : none;
	color : black;
}
th { background-color: #4d4d4d;
     padding : 20px;
color:white ;}
table,td {padding:20px;}
</style>
{% endblock %}
{%  block content %}
<table>
<tr> <th> Tâche </th>
<th> Dernier message </th>
<th> Auteur et date </th></tr>
<tr>
<td>

{%  for t in list_tasks %}
     <a href = "{%  url 'focus_task' id=t.id %}"> {{t.name}} </a> <br><br>
    {%  endfor %}

</td>
<td>


    {%  for c in ordered_comments %}
        {% if c == "empty" %}
            Aucun message <br><br>

        {%  else %}
            <span style="color:mediumpurple"><strong>{{ c.content }} </strong> </span> <br><br>
        {% endif %}
        {%  endfor %}

</td>
<td>
{% for c in ordered_comments %}
    {% if c == "empty" %}
    <br><br>
    {% else %}
par <strong>{{ c.user.username }}</strong> <i> le {{ c.submit_time }} </i> </li><br><br>
    {%  endif %}
{%  endfor %}
</td>
</tr>
</table>
{% endblock %}

taskmanager/templates/taskmanager/avancement.html
{%  extends "base.html" %}
{%  block content %}
<h1> Modifiez le pourcentage d'avancement de votre tâche </h1>
<form enctype="multipart/form-data" method="post" action="">
    {% csrf_token %}
    0%
    <input type="range" id="completed" name="completed" value="{{ task.completed }}">
    100%
    <br><br>
    <input type="submit" value="Modifier l'avancement"/>
</form>
{%  endblock %}

taskmanager/templates/taskmanager/connect.html
<!-- Page de connexion ave une vue manuelle -->
{% extends 'header.html' %}

{% block css %}
	<style>
		html, body {
		  height: 100%;
		}
		.background {
			background: linear-gradient(to bottom, #ffffff 0%, #505050 100%);
			height: 100%;
		}
		#authbox {
			background: linear-gradient(to bottom, #ffffff 0%, #505050 100%);
			box-shadow: 5px 5px 5px black;
		}
	</style>
{% endblock %}

{% block script %}
	<script>
		$(document).ready(function() {
				{% if error %}
					$('.toast').toast('show');
				{% endif %}
			})
	</script>
{% endblock %}



{% block content %}

	<div class="container">
		<div class="toast" data-delay="3000" style="position: absolute; bottom: 1rem; right: 1rem; min-width:250px; z-index: 1000;" aria-live="assertive" aria-atomic="true">
			<div class="toast-header" style="background-color: #fc9d9d">
				<i class="fa fa-warning"></i>
				<strong class="mr-auto ml-2" style="color: #555555">Connexion</strong>
				<button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Fermer"><span aria-hidden="true">&times;</span></button>
			</div>
			<div class="toast-body">
				Échec de la connexion !
			</div>
		</div>
	</div>


   <div class="background">
		<div class="d-flex justify-content-center align-items-center" style="height:100%;">
			<div id="authbox" class="py-4 px-5 border rounded border-dark">
				<div class="row">

					<div class="col-7">
						<h5 class="mb-4">Authentification</h5>
				      <form method="post" action="{% url "connect" %}">
				         {% csrf_token %}
				         <p>{{ form.username }}</p>
							<p>{{ form.password }}</p>
				         <input type="submit" value="Se connecter"/>
				      </form>
					</div>

					<div class="d-none d-md-block col-5 container-fluid">
						<div class="text-center">
							<img id="logo" title="Violin" src="/static/pictures/calendar-check-solid.svg" class="img-fluid m-4" />
							<h3>Gestionnaire de projets</h3>
						</div>
					</div>
				</div>

		   </div>


		</div>

	</div>
{% endblock %}

taskmanager/templates/taskmanager/connect_gen.html
<!-- Page pour se connecter avec une vue générique -->
{% extends 'header.html' %}

{% block css %}
	<style>
		html, body {
		  height: 100%;
		}
		.background {
			background: linear-gradient(to bottom, #ffffff 0%, #505050 100%);
			height: 100%;
		}
		#authbox {
			background: linear-gradient(to bottom, #ffffff 0%, #505050 100%);
			box-shadow: 5px 5px 5px black;
		}
	</style>
{% endblock %}

{% block script %}
	<script>
		$(document).ready(function() {
				{% if error %}
					$('.toast').toast('show');
				{% endif %}
			})
	</script>
{% endblock %}



{% block content %}

	<div class="container">
		<div class="toast" data-delay="3000" style="position: absolute; bottom: 1rem; right: 1rem; min-width:250px; z-index: 1000;" aria-live="assertive" aria-atomic="true">
			<div class="toast-header" style="background-color: #fc9d9d">
				<i class="fa fa-warning"></i>
				<strong class="mr-auto ml-2" style="color: #555555">Connexion</strong>
				<button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Fermer"><span aria-hidden="true">&times;</span></button>
			</div>
			<div class="toast-body">
				Échec de la connexion !
			</div>
		</div>
	</div>


   <div class="background">
		<div class="d-flex justify-content-center align-items-center" style="height:100%;">
			<div id="authbox" class="py-4 px-5 border rounded border-dark">
				<div class="row">

					<div class="col-12 col-md-7">
						<h5 class="mb-4">Authentification</h5>
				      <form method="post" action=".">
				         {% csrf_token %}
				         <p>{{ form.username }}</p>
							<p>{{ form.password }}</p>
				         <input type="submit" value="Se connecter"/>
				      </form>
					</div>

					<div class="d-none d-md-block col-5 container-fluid">
						<div class="text-center">
							<img id="logo" title="Violin" src="/static/pictures/calendar-check-solid.svg" class="img-fluid m-4" />
							<h3>Gestionnaire de projets</h3>
						</div>
					</div>
				</div>

		   </div>


		</div>

	</div>
{% endblock %}

taskmanager/templates/taskmanager/focus_project.html
<!-- Vue individuelle d'un projet -->
{% extends "base.html"%}

{% block css %}
<style>
a:hover {
	text-decoration: none;
	color : black;
}
</style>
{% endblock %}


{% block script%}
<script>
   $(document).ready(
      function() {
         document.getElementById("projects-nav_item").classList.add("active");
			{% if show_toast %}
				$('.toast').toast('show');
			{% endif %}
      }
   )
</script>
{%endblock%}



{% block content %}

<!-- ================ TOAST Tache supprimee (on revient de la page formtask, en mode MODIFY ) ================ -->
{% if show_toast %}
	<div class="container">
	   <div class="toast" data-delay="3000" style="position: fixed; bottom: 1rem; right: 1rem; min-width:250px; z-index:5000" aria-live="assertive" aria-atomic="true">
	      <div class="toast-header" style="background-color: #c9c9c9">
	         <i class="fa fa-times"></i>
	         <strong class="mr-auto ml-2">Suppression de la tâche</strong>
	         <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Fermer"><span aria-hidden="true">&times;</span></button>
	      </div>
	      <div class="toast-body" >
	         {{ deleted_task }} a été supprimé
	      </div>
	   </div>
	</div>
{% endif %}



<div class="m-sm-5">
   <a href="{% url "projects" %}"><i class="fa fa-angle-double-left"></i> Mes projets</a>

	<!-- HEADER Presentation du Projet -->
   <div class="mx-5  my-3">
		<div class="row">
			<div class="col-11">
				<h3 style="display:inline" class="mr-4">{{ project }}</h3><em>Projet {{ project.get_public_display }}</em>
			</div>
			<div class="col-1 text-right">
					<h3><a href="{% url "manageproject" id=project.id %}"><i class="fa fa-wrench"></i></a></h3>
			</div>
		</div>

		<!-- Liste des membres -->
      <table class="table">
         <tbody>
            <tr>
               <th class="thead-dark">Membres</th>
               <td>
                  {% for member in project.members.all %}
                  	<span class="badge badge-secondary">{{ member.first_name }} {{ member.last_name }}</span>
                  {% endfor %}
               </td>
            </tr>
         </tbody>
      </table>
   </div>

	<!-- HEADER Taches -->
	<div class="row">
		<div class="col-11">
			<h4 class="mb-3">Tâches</h4>
		</div>
		<div class="col-1 text-right">
			<h4><a href="{% url "newtask" id_project=project.id %}"><i class="fa fa-plus-square"></i></a></h4>
		</div>
	</div>


     <!-- Lien vers un tri des tâches selon leur assignee -->
    <a href="{% url 'distincttasks' ide=project.id %}"> Afficher séparément mes tâches et celles des autres utilisateurs </a>
    <br><br>

    <!-- Lien vers le tri des tâches selon leur dernière activité -->
    <a href="{% url 'activities' ide=project.id %}"> Afficher les tâches triées par ordre chronologique de la dernière activité </a>
    <br><br>

   <table class="table table-hover">

      <thead class="thead-dark">
         <tr>
            <th scope="col" class="col-1">Priorité</th>
            <th scope="col" class="col-3">Tâche</th>
             <th scope="col"> Avancement </th>
            <th class="d-none d-lg-table-cell" scope="col">Responsable</th>
            <th class="d-none d-xl-table-cell" scope="col">Deadline</th>
            <th class="d-none d-lg-table-cell" scope="col">Statut</th>
				<th scope="col" class="d-none d-md-table-cell col-1">Détails</th>
            <th scope="col" class="d-none d-sm-table-cell col-1">Éditer</th>
         </tr>
      </thead>



      <tbody>
         {% for task in tasks %}
         <tr>
            <td>{{ task.priority }}</td>
				<td><a href={% url "focus_task" id=task.id %}>{{ task.name }}</a></td>

             <td > <a id="{{ task.id }}" href="{%  url 'form_avancement' id=task.id %}">{{ task.completed }}% </a></td>
            <script>
                    if({{task.completed}}>=66) {
                        document.getElementById("{{ task.id }}").style.color = "green";
                    }
                    if({{task.completed}}>=33 && {{ task.completed }}<66) {
                        document.getElementById("{{ task.id }}").style.color = "orange";
                    }
                 if({{task.completed}}<33) {
                        document.getElementById("{{ task.id }}").style.color = "red";
                    }

             </script>
            <td class="d-none d-lg-table-cell">{{ task.user.last_name }}</td>
            <td class="d-none d-xl-table-cell">{{ task.due_date|date }}</td>
            <td class="d-none d-lg-table-cell">{{ task.status }}</td>
				<td class="d-none d-md-table-cell"><a href="{% url "focus_task" id=task.id %}"<i class="fa fa-search"></i></td>
            <td class="d-none d-sm-table-cell"><a href="{% url "managetask" id=task.id %}"<i class="fa fa-edit"></i></td>
         </tr>

         {% empty %}
         	<tr><td colspan=7>Pas de tâches</td></tr>

         {% endfor %}

      </tbody>

   </table>

</div>

{% endblock %}

taskmanager/templates/taskmanager/list_members_project.html
{% extends "base.html"%}
{% load humanize %}
{% load static %}
{% block css %}
<style>
    table, th, td {
        font-size : 120% ;
        padding : 20px ;
        border : 1px solid black;

    }
    .grid-container {
  display: grid;
        grid-column-gap:20px;
        grid-row-gap:15px;
  grid-template-columns: auto auto auto;

  padding: 30px;
}
    .grid-item {
        padding : 20px ;
    }
    </style>
      {% endblock %}

{% block content %}

    <div class="grid-container">
    {% for p in proj %}
        <div class="grid-item" style="background-color:#4d4d4d">
        <h2> <a style="color:white" href="{%url 'focus_project' id=p.id %}"> {{p.name}} </a></h2><br>
        <ul>
        {% for m in p.members.all %}
        <li style="font-size:120%"> <span style="background-color:lightgrey;padding:6px">  {{m.username}}  </span></li><br>
        {% endfor %}
    </ul></div>
    {% endfor %}
                       </div>


{% endblock %}

taskmanager/templates/taskmanager/projects.html
<!-- Vue globale des projects -->
{% extends "base.html"%}

{% block script%}
	<script>
		$(document).ready(
			function() {
				document.getElementById("projects-nav_item").classList.add("active");
				{% if show_toast %}
	            $('.toast').toast('show');
	         {% endif %}
			}
		)
	</script>
{%endblock%}


{% block content %}

{% if show_toast %}

<!-- ================ TOAST de projet supprimé (on vient de formproject en mode MODIFY ) ================ -->
<div class="container">
   <div class="toast" data-delay="3000" style="position: absolute; bottom: 1rem; right: 1rem; min-width:250px;" aria-live="assertive" aria-atomic="true">
      <div class="toast-header" style="background-color: #c9c9c9">
         <i class="fa fa-times"></i>
         <strong class="mr-auto ml-2">Suppression du projet</strong>
         <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Fermer"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="toast-body" >
         {{ deleted_project }} a été supprimé
      </div>
   </div>
</div>

{% endif %}




<div class=article>
	<h3 class="mx-5">Mes projets</h3>
	<em>Ici s'affichent tous vos projets privés et tous les projets publics</em>
	<br/><br/>


	<table class="table table-hover">


	<thead class="thead-dark">
		<tr>
            <th> Avancement </th>
			<th scope="col">Projet</th>
			<th class="d-none d-lg-table-cell" scope="col">Membres</th>
			<th class="d-none d-lg-table-cell text-right" scope="col">Partage</th>
		</tr>
	</thead>


	<tbody>
		{% for project in projects_list %}
			<tr>

                <td id="{{ project.id }}"> {{ project.completed }}%</td>
                <script>
                    if({{project.completed}}>=66) {
                        document.getElementById("{{ project.id }}").style.color = "green";
                    }
                    if({{project.completed}}>=33 && {{ project.completed }}<66) {
                        document.getElementById("{{ project.id }}").style.color = "orange";
                    }
                 if({{project.completed}}<33) {
                        document.getElementById("{{ project.id }}").style.color = "red";
                    }

             </script>
				<td><a href="{% url "focus_project" id=project.id %}">{{ project.name }}</a></td>
				<td class="d-none d-lg-table-cell">
					{% for member in project.members.all %}
						<span class="badge badge-secondary">{{ member.first_name }} {{ member.last_name }}</span>
					{% endfor %}
				</td>
				<td class="d-none d-lg-table-cell text-right">
					{% if project.public == "PR" %}
						<span class="badge badge-danger">
					{% else %}
						<span class="badge badge-info">
					{% endif %}
						{{ project.get_public_display|title }}</span>
				</td>
			</tr>

		{% empty %}
			<tr><td colspan=2>Pas de projet</td></tr>

		{% endfor %}
	</tbody>

</table>

</div>

{% endblock %}